# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_original', models.BooleanField(db_index=True, default=False)),
                ('length', models.TextField()),
                ('count', models.BigIntegerField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_original', models.BooleanField(db_index=True, default=False)),
                ('position', models.TextField()),
                ('quality', models.DecimalField(decimal_places=4, max_digits=7)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_original', models.BooleanField(db_index=True, default=False)),
                ('rank', models.PositiveSmallIntegerField(db_index=True)),
                ('total_bp', models.BigIntegerField()),
                ('coverage', models.DecimalField(decimal_places=2, max_digits=7)),
                ('read_total', models.BigIntegerField(default=0)),
                ('read_min', models.PositiveIntegerField(default=0)),
                ('read_mean', models.DecimalField(decimal_places=4, default=0.0, max_digits=11)),
                ('read_std', models.DecimalField(decimal_places=4, default=0.0, max_digits=11)),
                ('read_median', models.PositiveIntegerField(default=0)),
                ('read_max', models.PositiveIntegerField(default=0)),
                ('read_25th', models.PositiveIntegerField(default=0)),
                ('read_75th', models.PositiveIntegerField(default=0)),
                ('qual_mean', models.DecimalField(decimal_places=4, max_digits=7)),
                ('qual_std', models.DecimalField(decimal_places=4, max_digits=7)),
                ('qual_median', models.PositiveIntegerField()),
                ('qual_25th', models.PositiveIntegerField()),
                ('qual_75th', models.PositiveIntegerField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together=set([('sample', 'is_original')]),
        ),
        migrations.AlterUniqueTogether(
            name='quality',
            unique_together=set([('sample', 'is_original')]),
        ),
        migrations.AlterUniqueTogether(
            name='length',
            unique_together=set([('sample', 'is_original')]),
        ),
    ]
