# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='length',
            unique_together=set([('sample', 'is_original', 'length')]),
        ),
        migrations.AlterUniqueTogether(
            name='quality',
            unique_together=set([('sample', 'is_original', 'position')]),
        ),
    ]
