# Generated by Django 2.0 on 2017-12-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
        ('sample', '0002_md5'),
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='version',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sequence_summary_version', to='version.Version'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='summary',
            unique_together={('sample', 'version', 'stage')},
        ),
    ]
