# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='qual_per_base',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='read_lengths',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
