# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0002_auto_20160504_1135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='length',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='length',
            name='sample',
        ),
        migrations.AlterUniqueTogether(
            name='quality',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='quality',
            name='sample',
        ),
        migrations.DeleteModel(
            name='Length',
        ),
        migrations.DeleteModel(
            name='Quality',
        ),
    ]
