# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_tag',
            field=models.TextField(db_index=True, default=b''),
        ),
    ]
