# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='md5sum',
            field=models.CharField(default=b'', max_length=32, unique=True),
        ),
    ]
