# Generated by Django 2.0 on 2017-12-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sample',
            name='sample_samp_documen_70686d_gin',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='document',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='md5sum',
        ),
    ]
