# Generated by Django 2.0 on 2017-12-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20171207_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='md5sum',
            field=models.CharField(default='', max_length=32),
        ),
    ]
