# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_sample_sample_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='pubdate',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='reference_ids',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.TextField(),
        ),
    ]
