# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20160518_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='pubdate',
        ),
    ]
