# Generated by Django 2.0 on 2018-03-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_metadata_metadatafields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
