# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_auto_20160518_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibiotic', models.TextField()),
                ('test', models.TextField()),
                ('unit', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('susceptible', models.TextField()),
                ('intermediate', models.TextField()),
                ('resistant', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ToMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ToResistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('phenotype', models.TextField()),
                ('resistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Resistance')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Sample')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.ResistanceSpecification')),
            ],
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='clindamycin_mic',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='contact_link',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='daptomycin_mic',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='funding_agency',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='funding_agency_link',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='host_age',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='host_gender',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='host_health',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='host_name',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='isolation_city',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='isolation_country',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='isolation_date',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='isolation_region',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='levofloxacin_mic',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='linezolid_mic',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='oxacillin_mic',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='penicillin_mic',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='publication_link',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='pubmed_id',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='rifampin_mic',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='sequencing_center',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='sequencing_center_link',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='sequencing_date',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='sequencing_libaray_method',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='sequencing_platform',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='source',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='strain',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='tetracycline_mic',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='trimethoprim_mic',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='vancomycin_mic',
        ),
        migrations.AddField(
            model_name='metadata',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadata',
            name='field',
            field=models.TextField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tometadata',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData'),
        ),
        migrations.AddField(
            model_name='tometadata',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Sample'),
        ),
        migrations.AlterUniqueTogether(
            name='resistancespecification',
            unique_together=set([('susceptible', 'intermediate', 'resistant')]),
        ),
        migrations.AlterUniqueTogether(
            name='resistance',
            unique_together=set([('antibiotic', 'test')]),
        ),
    ]
