# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_auto_20160602_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='resistancespecification',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='resistance',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='resistance',
            unique_together=set([('antibiotic', 'test', 'unit')]),
        ),
        migrations.AlterUniqueTogether(
            name='resistancespecification',
            unique_together=set([('susceptible', 'intermediate', 'resistant', 'comment')]),
        ),
    ]
