# Generated by Django 2.0 on 2018-03-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_auto_20180315_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='reason',
            field=models.TextField(),
        ),
    ]
