# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_remove_sample_db_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnaMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_accession', models.TextField()),
                ('study_title', models.TextField(help_text=b'Title of the study as would be used in a publication.')),
                ('study_alias', models.TextField()),
                ('secondary_study_accession', models.TextField()),
                ('sample_accession', models.TextField()),
                ('secondary_sample_accession', models.TextField()),
                ('submission_accession', models.TextField()),
                ('experiment_accession', models.TextField()),
                ('experiment_title', models.TextField(help_text=b'Short text that can be used to call out experiment records in searches or in displays.')),
                ('experiment_alias', models.TextField()),
                ('tax_id', models.PositiveIntegerField(help_text=b'NCBI Taxonomy Identifier.')),
                ('scientific_name', models.TextField(help_text=b'Scientific name of sample that distinguishes its taxonomy.')),
                ('instrument_platform', models.TextField(help_text=b'Which sequencing platform and platform-specific runtime parameters.')),
                ('instrument_model', models.TextField(help_text=b'Specific model of the platform used for sequencing.')),
                ('library_layout', models.TextField(help_text=b'Single, paired or other configuration of reads.')),
                ('library_strategy', models.TextField(help_text=b'Sequencing technique intended for this library.')),
                ('library_selection', models.TextField(help_text=b'')),
                ('center_name', models.TextField(help_text=b'Sequencing center that submitted the sample to ENA/SRA')),
                ('center_link', models.TextField(help_text=b'Sequencing center link that submitted the sample to ENA/SRA')),
                ('first_public', models.DateField(help_text=b'Date sample was submitted to ENA/SRA.')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Sample')),
            ],
        ),
        migrations.RemoveField(
            model_name='tometadata',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='tometadata',
            name='sample',
        ),
        migrations.DeleteModel(
            name='ToMetaData',
        ),
    ]
