# Generated by Django 2.0 on 2018-04-08 23:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_auto_20180316_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='document',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['document'], name='sample_meta_documen_7193c2_gin'),
        ),
    ]
