# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_auto_20170223_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='enametadata',
            name='biosample_center_name',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='enametadata',
            name='biosample_first_public',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='enametadata',
            name='biosample_scientific_name',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='enametadata',
            name='biosample_tax_id',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='enametadata',
            name='center_name',
            field=models.TextField(help_text=b'Sequencing center that submitted the sample to ENA/SRA'),
        ),
        migrations.AlterField(
            model_name='enametadata',
            name='first_public',
            field=models.DateField(help_text=b'Date sample was submitted to ENA/SRA.'),
        ),
        migrations.AlterField(
            model_name='enametadata',
            name='scientific_name',
            field=models.TextField(help_text=b'Scientific name of sample that distinguishes its taxonomy.'),
        ),
        migrations.AlterField(
            model_name='enametadata',
            name='tax_id',
            field=models.PositiveIntegerField(help_text=b'NCBI Taxonomy Identifier.'),
        ),
    ]
