# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-08 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_auto_20170223_2311'),
        ('sample', '0009_auto_20170222_1855'),
    ]

    operations = [
    ]
