# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-15 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='sample',
        ),
        migrations.AddField(
            model_name='enametadata',
            name='contains_ena_metadata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sample.Sample'),
        ),
        migrations.DeleteModel(
            name='MetaData',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
