# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-15 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_auto_20170515_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contains_ena_metadata', models.BooleanField(default=True)),
                ('study_accession', models.TextField(default=b'')),
                ('study_title', models.TextField(default=b'', help_text=b'Title of the study as would be used in a publication.')),
                ('study_alias', models.TextField(default=b'')),
                ('secondary_study_accession', models.TextField(default=b'')),
                ('sample_accession', models.TextField(default=b'')),
                ('secondary_sample_accession', models.TextField(default=b'')),
                ('submission_accession', models.TextField(default=b'')),
                ('experiment_accession', models.TextField(default=b'')),
                ('experiment_title', models.TextField(default=b'', help_text=b'Short text that can be used to call out experiment records in searches or in displays.')),
                ('experiment_alias', models.TextField(default=b'')),
                ('tax_id', models.PositiveIntegerField(default=b'', help_text=b'NCBI Taxonomy Identifier.')),
                ('scientific_name', models.TextField(default=b'', help_text=b'Scientific name of sample that distinguishes its taxonomy.')),
                ('instrument_platform', models.TextField(default=b'', help_text=b'Which sequencing platform and platform-specific runtime parameters.')),
                ('instrument_model', models.TextField(default=b'', help_text=b'Specific model of the platform used for sequencing.')),
                ('library_layout', models.TextField(default=b'', help_text=b'Single, paired or other configuration of reads.')),
                ('library_strategy', models.TextField(default=b'', help_text=b'Sequencing technique intended for this library.')),
                ('library_selection', models.TextField(default=b'', help_text=b'')),
                ('center_name', models.TextField(default=b'', help_text=b'Sequencing center that submitted the sample to ENA/SRA')),
                ('center_link', models.TextField(default=b'', help_text=b'Sequencing center link that submitted the sample to ENA/SRA')),
                ('first_public', models.DateField(default=b'', help_text=b'Date sample was submitted to ENA/SRA.')),
                ('cell_line', models.TextField(default=b'')),
                ('collected_by', models.TextField(default=b'')),
                ('collection_date', models.TextField(default=b'')),
                ('country', models.TextField(default=b'')),
                ('description', models.TextField(default=b'')),
                ('environmental_sample', models.TextField(default=b'')),
                ('biosample_first_public', models.TextField(default=b'')),
                ('germline', models.TextField(default=b'')),
                ('isolate', models.TextField(default=b'')),
                ('isolation_source', models.TextField(default=b'')),
                ('location', models.TextField(default=b'')),
                ('serotype', models.TextField(default=b'')),
                ('serovar', models.TextField(default=b'')),
                ('sex', models.TextField(default=b'')),
                ('submitted_sex', models.TextField(default=b'')),
                ('strain', models.TextField(default=b'')),
                ('sub_species', models.TextField(default=b'')),
                ('tissue_type', models.TextField(default=b'')),
                ('biosample_tax_id', models.TextField(default=b'')),
                ('biosample_scientific_name', models.TextField(default=b'')),
                ('sample_alias', models.TextField(default=b'')),
                ('checklist', models.TextField(default=b'')),
                ('biosample_center_name', models.TextField(default=b'')),
                ('environment_biome', models.TextField(default=b'')),
                ('environment_feature', models.TextField(default=b'')),
                ('environment_material', models.TextField(default=b'')),
                ('project_name', models.TextField(default=b'')),
                ('host', models.TextField(default=b'')),
                ('host_tax_id', models.TextField(default=b'')),
                ('host_status', models.TextField(default=b'')),
                ('host_sex', models.TextField(default=b'')),
                ('submitted_host_sex', models.TextField(default=b'')),
                ('host_body_site', models.TextField(default=b'')),
                ('investigation_type', models.TextField(default=b'')),
                ('sequencing_method', models.TextField(default=b'')),
                ('broker_name', models.TextField(default=b'')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sample.Sample')),
            ],
        ),
    ]
