# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-15 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enametadata',
            name='sample',
        ),
        migrations.DeleteModel(
            name='EnaMetaData',
        ),
    ]
