# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-10 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0014_auto_20170515_1848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('user', 'tag')]),
        ),
    ]
