# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:47
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0015_auto_20170610_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='document',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=django.contrib.postgres.indexes.GinIndex(fields=[b'document'], name='sample_samp_documen_70686d_gin'),
        ),
    ]
