# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0016_auto_20170816_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='country',
            new_name='coordinates',
        ),
    ]
