# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0017_auto_20170817_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='city',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='metadata',
            name='country',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='metadata',
            name='state',
            field=models.TextField(default=b''),
        ),
    ]
