# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sample', '0019_auto_20170817_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDataHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('field', models.TextField()),
                ('previous', models.TextField()),
                ('current', models.TextField()),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sample.Sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
