# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus_name', models.CharField(max_length=4)),
                ('locus_id', models.PositiveSmallIntegerField()),
                ('bitscore', models.PositiveSmallIntegerField()),
                ('slen', models.PositiveSmallIntegerField()),
                ('length', models.PositiveSmallIntegerField()),
                ('gaps', models.PositiveSmallIntegerField()),
                ('mismatch', models.PositiveSmallIntegerField()),
                ('pident', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evalue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st', models.PositiveIntegerField(unique=True)),
                ('arcc', models.PositiveIntegerField()),
                ('aroe', models.PositiveIntegerField()),
                ('glpf', models.PositiveIntegerField()),
                ('gmk', models.PositiveIntegerField()),
                ('pta', models.PositiveIntegerField()),
                ('tpi', models.PositiveIntegerField()),
                ('yqil', models.PositiveIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Srst2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_original', models.TextField()),
                ('st_stripped', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_exact', models.BooleanField(db_index=True, default=False)),
                ('arcc', models.TextField()),
                ('aroe', models.TextField()),
                ('glpf', models.TextField()),
                ('gmk', models.TextField()),
                ('pta', models.TextField()),
                ('tpi', models.TextField()),
                ('yqil', models.TextField()),
                ('mismatches', models.TextField()),
                ('uncertainty', models.TextField()),
                ('depth', models.DecimalField(decimal_places=3, max_digits=8)),
                ('maxMAF', models.DecimalField(decimal_places=7, max_digits=11)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='blast',
            unique_together=set([('sample', 'locus_name', 'locus_id')]),
        ),
    ]
