# Generated by Django 2.0 on 2017-12-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus_name', models.CharField(max_length=4)),
                ('locus_id', models.PositiveSmallIntegerField()),
                ('bitscore', models.PositiveSmallIntegerField()),
                ('slen', models.PositiveSmallIntegerField()),
                ('length', models.PositiveSmallIntegerField()),
                ('gaps', models.PositiveSmallIntegerField()),
                ('mismatch', models.PositiveSmallIntegerField()),
                ('pident', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evalue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st', models.PositiveIntegerField(unique=True)),
                ('arcc', models.PositiveIntegerField()),
                ('aroe', models.PositiveIntegerField()),
                ('glpf', models.PositiveIntegerField()),
                ('gmk', models.PositiveIntegerField()),
                ('pta', models.PositiveIntegerField()),
                ('tpi', models.PositiveIntegerField()),
                ('yqil', models.PositiveIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='blast',
            unique_together={('sample', 'locus_name', 'locus_id')},
        ),
    ]
