# Generated by Django 2.0 on 2017-12-15 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_md5'),
        ('version', '0001_initial'),
        ('mlst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st', models.PositiveIntegerField(db_index=True)),
                ('ariba', models.PositiveIntegerField(db_index=True)),
                ('mentalist', models.PositiveIntegerField(db_index=True)),
                ('blast', models.PositiveIntegerField(db_index=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlst_sample', to='sample.Sample')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlst_version', to='version.Version')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ariba', models.TextField()),
                ('mentalist', models.TextField()),
                ('blast', models.TextField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlst_report_sample', to='sample.Sample')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlst_report_version', to='version.Version')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='blast',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='blast',
            name='sample',
        ),
        migrations.DeleteModel(
            name='Blast',
        ),
    ]
