# Generated by Django 2.0 on 2017-12-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_md5'),
        ('version', '0001_initial'),
        ('mlst', '0002_auto_20171215_0652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mlst',
            unique_together={('sample', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('sample', 'version')},
        ),
    ]
