# Generated by Django 2.0 on 2018-03-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlst', '0004_auto_20180319_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlst',
            name='support',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mlst.Support'),
            preserve_default=False,
        ),
    ]
