# Generated by Django 2.0 on 2018-03-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlst', '0005_mlst_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlst',
            old_name='is_novel',
            new_name='predicted_novel',
        ),
    ]
