# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cassette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('header', models.TextField()),
                ('length', models.PositiveIntegerField()),
                ('meca_start', models.PositiveIntegerField(default=0)),
                ('meca_stop', models.PositiveIntegerField(default=0)),
                ('meca_length', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum', models.PositiveIntegerField()),
                ('mean', models.DecimalField(decimal_places=2, max_digits=5)),
                ('median', models.PositiveIntegerField()),
                ('maximum', models.PositiveIntegerField()),
                ('meca_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('meca_minimum', models.PositiveIntegerField(default=0)),
                ('meca_mean', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('meca_median', models.PositiveIntegerField(default=0)),
                ('meca_maximum', models.PositiveIntegerField(default=0)),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sccmec.Cassette')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cassette',
            unique_together=set([('name', 'header')]),
        ),
        migrations.AlterUniqueTogether(
            name='coverage',
            unique_together=set([('sample', 'cassette')]),
        ),
    ]
