# Generated by Django 2.0 on 2017-12-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
        ('sample', '0003_auto_20171215_2005'),
        ('sccmec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='version',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sccmec_coverage_version', to='version.Version'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coverage',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sccmec_coverage_sample', to='sample.Sample'),
        ),
        migrations.AlterUniqueTogether(
            name='coverage',
            unique_together={('sample', 'version', 'cassette')},
        ),
    ]
