# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sccmec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerBaseCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('coverage', models.PositiveIntegerField()),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sccmec.Cassette')),
            ],
        ),
    ]
