# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sccmec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='per_base_coverage',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
