# Generated by Django 2.0 on 2018-04-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sccmec', '0003_auto_20171218_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primers',
            name='contig',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='proteins',
            name='contig',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subtypes',
            name='contig',
            field=models.PositiveIntegerField(),
        ),
    ]
