# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_auto_20160420_1225'),
        ('sample', '0003_program'),
        ('staphopia', '0001_initial'),
        ('sccmec', '0003_perbasecoverage_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitscore', models.PositiveSmallIntegerField()),
                ('evalue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('identity', models.PositiveSmallIntegerField()),
                ('mismatch', models.PositiveSmallIntegerField()),
                ('gaps', models.PositiveSmallIntegerField()),
                ('hamming_distance', models.PositiveSmallIntegerField()),
                ('query_from', models.PositiveSmallIntegerField()),
                ('query_to', models.PositiveSmallIntegerField()),
                ('hit_from', models.PositiveIntegerField()),
                ('hit_to', models.PositiveIntegerField()),
                ('align_len', models.PositiveSmallIntegerField()),
                ('qseq', models.TextField()),
                ('hseq', models.TextField()),
                ('midline', models.TextField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembly.Contigs')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Program')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staphopia.BlastQuery')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitscore', models.PositiveSmallIntegerField()),
                ('evalue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('identity', models.PositiveSmallIntegerField()),
                ('mismatch', models.PositiveSmallIntegerField()),
                ('gaps', models.PositiveSmallIntegerField()),
                ('hamming_distance', models.PositiveSmallIntegerField()),
                ('query_from', models.PositiveSmallIntegerField()),
                ('query_to', models.PositiveSmallIntegerField()),
                ('hit_from', models.PositiveIntegerField()),
                ('hit_to', models.PositiveIntegerField()),
                ('align_len', models.PositiveSmallIntegerField()),
                ('qseq', models.TextField()),
                ('hseq', models.TextField()),
                ('midline', models.TextField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembly.Contigs')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Program')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staphopia.BlastQuery')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
