# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-08 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_auto_20160609_1139'),
        ('staphopia', '0001_initial'),
        ('sample', '0009_auto_20170222_1855'),
        ('sccmec', '0003_auto_20160504_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitscore', models.PositiveSmallIntegerField()),
                ('evalue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('identity', models.PositiveSmallIntegerField()),
                ('mismatch', models.PositiveSmallIntegerField()),
                ('gaps', models.PositiveSmallIntegerField()),
                ('hamming_distance', models.PositiveSmallIntegerField()),
                ('query_from', models.PositiveSmallIntegerField()),
                ('query_to', models.PositiveSmallIntegerField()),
                ('hit_from', models.PositiveIntegerField()),
                ('hit_to', models.PositiveIntegerField()),
                ('align_len', models.PositiveSmallIntegerField()),
                ('qseq', models.TextField()),
                ('hseq', models.TextField()),
                ('midline', models.TextField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembly.Contigs')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Program')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staphopia.BlastQuery')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Sample')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
