# Generated by Django 2.0 on 2017-12-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staphopia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
    ]
