# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staphopia', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blastquery',
            unique_together=set([('title', 'length')]),
        ),
    ]
