"""Insert Jellyfish output into the database."""
import sys

from django.core.management.base import BaseCommand

from kmer.models import String


class Command(BaseCommand):
    """Insert Kmer data generated by Jellyfish into the database."""

    help = 'Insert Kmer data generated by Jellyfish into the database.'

    _tables = ['kmer_string']

    def add_arguments(self, parser):
        """Command line arguements."""
        parser.add_argument('counts', metavar='UNIQ_COUNTS',
                            help='Text file of kmers specific to a partition.')
        parser.add_argument('partition', metavar='PARTITION',
                            help='Partition to insert kmers to.')

    def handle(self, *args, **opts):
        """Process kmers."""
        # Read count file
        kmers = []
        with open(opts['counts'], "r") as f:
            for line in f:
                kmers.append(line.rstrip())

        # Insert kmers
        new_kmers = String.objects.insert_into_partition(
            kmers, opts['partition']
        )
        print("{0} kmers added to kmer_string_{1}".format(
            new_kmers, opts['partition']
        ))
