""" Insert Jellyfish output into the database. """
from django.core.management.base import BaseCommand

from kmer.tools import jellyfish_dump, get_string_ids


class Command(BaseCommand):
    help = 'Insert Kmer data generated by Jellyfish into the database.'

    def add_arguments(self, parser):
        parser.add_argument('counts', metavar='UNIQ_COUNTS',
                            help='Jellyfish file of kmer counts.')

    def handle(self, *args, **opts):
        # Read count file
        jf_dump = jellyfish_dump(opts['counts'])
        kmers = []
        for line in jf_dump:
            if not line:
                continue
            kmer, count = line.rstrip().split()
            kmers.append(kmer)

        existing_kmers = get_string_ids(kmers)
        print('Total: {0}, Existing: {1}'.format(
            len(kmers), len(existing_kmers.keys())
        ))
