# Generated by Django 2.0 on 2017-12-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='toindel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tosnp',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='toindel',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='toindel',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='toindel',
            name='indel',
        ),
        migrations.RemoveField(
            model_name='tosnp',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='tosnp',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='tosnp',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='tosnp',
            name='snp',
        ),
    ]
