# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField()),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Reference')),
            ],
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='db_xref',
        ),
        migrations.AddField(
            model_name='indel',
            name='feature',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='variant.Feature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snp',
            name='feature',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='variant.Feature'),
            preserve_default=False,
        ),
    ]
