# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0002_auto_20160825_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confidence',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='counts',
            name='confidence',
        ),
        migrations.DeleteModel(
            name='Confidence',
        ),
    ]
