# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0002_auto_20160420_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='is_pseudo',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
