# Generated by Django 2.0 on 2017-12-19 03:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20171215_2005'),
        ('variant', '0002_auto_20171219_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='toindel',
            name='indel',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toindel',
            name='reference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='variant.Reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tosnp',
            name='reference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='variant.Reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tosnp',
            name='snp',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='toindel',
            unique_together={('sample', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='tosnp',
            unique_together={('sample', 'reference')},
        ),
    ]
