# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0003_annotation_is_pseudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='protein_id',
            field=models.CharField(default=b'not_applicable', max_length=24),
        ),
    ]
