# Generated by Django 2.0 on 2017-12-19 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
        ('variant', '0003_auto_20171219_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='counts',
            name='version',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='variant_count_version', to='version.Version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toindel',
            name='version',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='toindel_version', to='version.Version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tosnp',
            name='version',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tosnp_version', to='version.Version'),
            preserve_default=False,
        ),
    ]
