# Generated by Django 2.0 on 2018-03-05 19:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0005_auto_20171219_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True)),
                ('is_mlst_set', models.BooleanField(db_index=True, default=False)),
                ('nongenic_indel', models.PositiveIntegerField()),
                ('nongenic_snp', models.PositiveIntegerField()),
                ('indel', models.PositiveIntegerField()),
                ('synonymous', models.PositiveIntegerField()),
                ('nonsynonymous', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Reference')),
            ],
        ),
        migrations.RemoveField(
            model_name='snpcounts',
            name='snp',
        ),
        migrations.AddField(
            model_name='indel',
            name='members',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snp',
            name='members',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SNPCounts',
        ),
        migrations.AlterUniqueTogether(
            name='counts',
            unique_together={('reference', 'position', 'is_mlst_set')},
        ),
    ]
