# Generated by Django 2.0 on 2018-03-05 19:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0006_auto_20180305_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndelMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='SNPMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Reference')),
            ],
        ),
        migrations.RemoveField(
            model_name='indel',
            name='members',
        ),
        migrations.AlterField(
            model_name='snp',
            name='members',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='snpmember',
            name='snp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.SNP'),
        ),
        migrations.AddField(
            model_name='indelmember',
            name='indel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Indel'),
        ),
        migrations.AddField(
            model_name='indelmember',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Reference'),
        ),
        migrations.AlterUniqueTogether(
            name='snpmember',
            unique_together={('reference', 'snp')},
        ),
        migrations.AlterUniqueTogether(
            name='indelmember',
            unique_together={('reference', 'indel')},
        ),
    ]
