# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-15 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0007_auto_20170425_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceGenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('base', models.CharField(max_length=1)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Reference')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='referencegenome',
            unique_together=set([('reference', 'position', 'base')]),
        ),
    ]
