# Generated by Django 2.0 on 2018-03-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0007_auto_20180305_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='indelmember',
            name='count',
            field=models.PositiveIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snpmember',
            name='count',
            field=models.PositiveIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
