# Generated by Django 2.0 on 2018-03-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0008_auto_20180305_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indelmember',
            name='indel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Indel', unique=True),
        ),
        migrations.AlterField(
            model_name='snpmember',
            name='snp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.SNP', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='indelmember',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='snpmember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='indelmember',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='snpmember',
            name='reference',
        ),
    ]
