# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-15 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0008_auto_20170515_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='sequence',
            field=models.TextField(default=b''),
        ),
    ]
