# Generated by Django 2.0 on 2018-03-05 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0009_auto_20180305_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indelmember',
            name='indel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='variant.Indel'),
        ),
        migrations.AlterField(
            model_name='snpmember',
            name='snp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='variant.SNP'),
        ),
    ]
