# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-25 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0010_annotation_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='phase',
            new_name='strand',
        ),
    ]
