# Generated by Django 2.0 on 2018-03-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0011_auto_20180305_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snp',
            name='members',
        ),
        migrations.AddField(
            model_name='counts',
            name='annotation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='variant.Annotation'),
            preserve_default=False,
        ),
    ]
