# Generated by Django 2.0 on 2018-03-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0012_auto_20180306_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='start',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referencegenome',
            name='annotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='variant.Annotation'),
            preserve_default=False,
        ),
    ]
