# Generated by Django 2.0 on 2018-03-30 16:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0013_auto_20180330_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencegenome',
            name='sequence',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='referencegenome',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='referencegenome',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='referencegenome',
            name='base',
        ),
        migrations.RemoveField(
            model_name='referencegenome',
            name='position',
        ),
    ]
