# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '0007_remove_sample_db_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ena_name', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('experiment_accession', models.TextField(primary_key=True, serialize=False)),
                ('experiment_title', models.TextField()),
                ('experiment_alias', models.TextField()),
                ('sample_accession', models.TextField()),
                ('secondary_sample_accession', models.TextField()),
                ('submission_accession', models.TextField()),
                ('tax_id', models.TextField()),
                ('scientific_name', models.TextField()),
                ('instrument_platform', models.TextField(db_index=True, default=b'')),
                ('instrument_model', models.TextField()),
                ('library_layout', models.TextField()),
                ('library_strategy', models.TextField()),
                ('library_selection', models.TextField()),
                ('center_name', models.TextField()),
                ('coverage', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleScholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.TextField(db_index=True)),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('cluster_id', models.TextField()),
                ('url_citations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_accession', models.TextField(primary_key=True, serialize=False)),
                ('is_paired', models.BooleanField(default=False)),
                ('run_alias', models.TextField()),
                ('read_count', models.BigIntegerField()),
                ('base_count', models.BigIntegerField()),
                ('mean_read_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_public', models.TextField()),
                ('fastq_bytes', models.TextField()),
                ('fastq_md5', models.TextField()),
                ('fastq_aspera', models.TextField()),
                ('fastq_ftp', models.TextField()),
                ('experiment_accession', models.ForeignKey(db_column=b'experiment_accession', on_delete=django.db.models.deletion.CASCADE, to='ena.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_accession', models.TextField(primary_key=True, serialize=False)),
                ('secondary_study_accession', models.TextField()),
                ('study_title', models.TextField()),
                ('study_alias', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ToPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_accession', models.ForeignKey(db_column=b'experiment_accession', on_delete=django.db.models.deletion.CASCADE, to='ena.Experiment')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='sample.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='ToSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.TextField()),
                ('path', models.TextField()),
                ('status', models.TextField()),
                ('experiment_accession', models.OneToOneField(db_column=b'experiment_accession', on_delete=django.db.models.deletion.CASCADE, to='ena.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='study_accession',
            field=models.ForeignKey(db_column=b'study_accession', on_delete=django.db.models.deletion.CASCADE, to='ena.Study'),
        ),
    ]
