# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tosample',
            name='path',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tosample',
            name='server',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tosample',
            name='status',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tosample',
            name='sample_id',
        ),
    ]
