# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-20 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centernames',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
