# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-20 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0002_centernames_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centernames',
            name='ena_name',
            field=models.TextField(unique=True),
        ),
    ]
