# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0004_auto_20160724_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tosample',
            name='experiment_accession',
            field=models.OneToOneField(db_column=b'experiment_accession', on_delete=django.db.models.deletion.CASCADE, to='ena.Experiment'),
        ),
    ]
