# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-05 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0004_biosample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToSample',
            new_name='Status',
        ),
    ]
