# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0005_auto_20170605_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='SraLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(unique=True)),
                ('experiment_accession', models.OneToOneField(db_column=b'experiment_accession', on_delete=django.db.models.deletion.CASCADE, to='ena.Experiment')),
            ],
        ),
    ]
