# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0005_auto_20160724_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='coverage',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
