# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0006_auto_20160810_1619'),
    ]

    operations = [

    ]
