# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0007_auto_20170823_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='sralink',
            name='last_checked',
            field=models.DateField(auto_now=True),
        ),
    ]
