# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0007_remove_tosample_sample'),
    ]

    operations = [
    ]
