# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0008_sralink_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sralink',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
