# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-07 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0008_remove_tosample_sample'),
    ]

    operations = [

    ]
