# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-08 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0009_remove_tosample_sample'),
    ]

    operations = [

    ]
