# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0010_sralink_is_queried'),
    ]

    operations = [
        migrations.AddField(
            model_name='topublication',
            name='google_scholar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topublication',
            name='sra_to_pubmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topublication',
            name='text_mining',
            field=models.BooleanField(default=False),
        ),
    ]
