# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0011_auto_20170823_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleScholarStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.TextField(db_index=True, unique=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('is_queried', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='googlescholar',
            name='is_queried',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlescholar',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
