# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0012_auto_20170824_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlescholar',
            name='is_queried',
        ),
        migrations.RemoveField(
            model_name='googlescholar',
            name='last_checked',
        ),
    ]
