# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ena', '0013_auto_20170824_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlescholar',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='googlescholar',
            name='url_citations',
        ),
    ]
