# Generated by Django 2.0 on 2018-01-22 22:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '0003_auto_20171215_2005'),
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('gene', django.contrib.postgres.fields.jsonb.JSONField()),
                ('protein', django.contrib.postgres.fields.jsonb.JSONField()),
                ('rna', django.contrib.postgres.fields.jsonb.JSONField()),
                ('blast', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_sample', to='sample.Sample')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_version', to='version.Version')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inference', models.TextField(db_index=True)),
                ('product', models.TextField(db_index=True)),
                ('note', models.TextField(db_index=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inference',
            unique_together={('inference', 'product', 'note', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('sample', 'version')},
        ),
    ]
