# Generated by Django 2.0 on 2018-01-31 22:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20171215_2005'),
        ('version', '0001_initial'),
        ('annotation', '0002_annotation_repeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_repeat_sample', to='sample.Sample')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_repeat_version', to='version.Version')),
            ],
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='repeat',
        ),
        migrations.AlterUniqueTogether(
            name='repeat',
            unique_together={('sample', 'version')},
        ),
    ]
