# Generated by Django 2.0 on 2018-01-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmlst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
    ]
