# Generated by Django 2.0 on 2018-03-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pmid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
