# Generated by Django 2.0 on 2017-12-16 07:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20171215_2005'),
        ('version', '0001_initial'),
        ('plasmid', '0002_auto_20171216_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('graph', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plasmid_sequence_sample', to='sample.Sample')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plasmid_sequence_version', to='version.Version')),
            ],
        ),
        migrations.RenameField(
            model_name='contig',
            old_name='name',
            new_name='spades',
        ),
        migrations.AddField(
            model_name='contig',
            name='staphopia',
            field=models.TextField(db_index=True, default=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='contig',
            name='sequence',
        ),
        migrations.AlterUniqueTogether(
            name='contig',
            unique_together={('sample', 'version', 'spades')},
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together={('sample', 'version')},
        ),
    ]
