# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import kmer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '0003_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', kmer.models.FixedCharField(max_length=31, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StringTmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', kmer.models.FixedCharField(max_length=31, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('singletons', models.PositiveIntegerField()),
                ('new_kmers', models.PositiveIntegerField()),
                ('runtime', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
        ),
    ]
