# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='new_kmers',
        ),
    ]
