# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmer', '0002_remove_total_new_kmers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='runtime',
        ),
    ]
