# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kmer', '0003_remove_total_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Sample', unique=True),
        ),
    ]
