# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kmer', '0004_auto_20160513_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sample.Sample'),
        ),
    ]
