# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-15 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmer', '0005_auto_20160513_1643'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='count',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='count',
            name='sample',
        ),
        migrations.DeleteModel(
            name='String',
        ),
        migrations.DeleteModel(
            name='StringTmp',
        ),
        migrations.DeleteModel(
            name='Count',
        ),
    ]
