# Generated by Django 2.0 on 2018-01-30 23:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '0003_auto_20171215_2005'),
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ariba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ariba', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance_ariba_sample', to='sample.Sample')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance_ariba_version', to='version.Version')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('resistance_class', models.TextField(db_index=True)),
                ('mechanism', models.TextField()),
                ('ref_name', models.TextField()),
                ('database', models.TextField()),
                ('headers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
    ]
