# Generated by Django 2.0 on 2018-01-31 16:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
        ('sample', '0003_auto_20171215_2005'),
        ('resistance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AribaSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequences', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance_aribaseq_sample', to='sample.Sample')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance_aribaseq_version', to='version.Version')),
            ],
        ),
        migrations.RenameField(
            model_name='ariba',
            old_name='ariba',
            new_name='results',
        ),
    ]
