# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variant', '0001_initial'),
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.TextField(unique=True)),
                ('entry_name', models.TextField()),
                ('length', models.PositiveIntegerField()),
                ('is_rep', models.BooleanField()),
                ('is_seed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('aa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('sequence', models.TextField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('is_positive', models.BooleanField()),
                ('is_tRNA', models.BooleanField()),
                ('phase', models.PositiveSmallIntegerField()),
                ('dna', models.TextField()),
                ('aa', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Clusters')),
                ('contig', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gene.Contigs')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_id', models.PositiveIntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('is_positive', models.BooleanField()),
                ('is_tRNA', models.BooleanField()),
                ('phase', models.PositiveSmallIntegerField()),
                ('dna', models.TextField()),
                ('aa', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Clusters')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('sequence', models.TextField()),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Reference')),
            ],
        ),
        migrations.AddField(
            model_name='references',
            name='contig',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gene.ReferenceSequence'),
        ),
        migrations.AddField(
            model_name='references',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Reference'),
        ),
        migrations.AddField(
            model_name='clustermembers',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Clusters'),
        ),
        migrations.AddField(
            model_name='clustermembers',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene', to='gene.Names'),
        ),
        migrations.AddField(
            model_name='clustermembers',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Organism'),
        ),
        migrations.AddField(
            model_name='clustermembers',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='gene.Names'),
        ),
        migrations.AlterUniqueTogether(
            name='referencesequence',
            unique_together=set([('reference', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='references',
            unique_together=set([('reference', 'contig', 'cluster', 'start', 'end')]),
        ),
        migrations.AlterUniqueTogether(
            name='features',
            unique_together=set([('sample', 'contig', 'cluster', 'start', 'end')]),
        ),
        migrations.AlterUniqueTogether(
            name='contigs',
            unique_together=set([('sample', 'name')]),
        ),
    ]
