# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variant', '0001_initial'),
        ('assembly', '0001_initial'),
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitscore', models.PositiveSmallIntegerField()),
                ('evalue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('identity', models.PositiveSmallIntegerField()),
                ('mismatch', models.PositiveSmallIntegerField()),
                ('gaps', models.PositiveSmallIntegerField()),
                ('hamming_distance', models.PositiveSmallIntegerField()),
                ('query_from', models.PositiveSmallIntegerField()),
                ('query_to', models.PositiveSmallIntegerField()),
                ('query_len', models.PositiveSmallIntegerField()),
                ('hit_from', models.PositiveIntegerField()),
                ('hit_to', models.PositiveIntegerField()),
                ('align_len', models.PositiveSmallIntegerField()),
                ('qseq', models.TextField()),
                ('hseq', models.TextField()),
                ('midline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClusterMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.TextField(unique=True)),
                ('entry_name', models.TextField()),
                ('length', models.PositiveIntegerField()),
                ('is_rep', models.BooleanField()),
                ('is_seed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('aa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('is_positive', models.BooleanField()),
                ('is_tRNA', models.BooleanField()),
                ('is_rRNA', models.BooleanField()),
                ('phase', models.PositiveSmallIntegerField()),
                ('prokka_id', models.TextField()),
                ('dna', models.TextField()),
                ('aa', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Clusters')),
                ('contig', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='assembly.Contigs')),
            ],
        ),
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inference', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_id', models.PositiveIntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('is_positive', models.BooleanField()),
                ('is_tRNA', models.BooleanField()),
                ('phase', models.PositiveSmallIntegerField()),
                ('dna', models.TextField()),
                ('aa', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Clusters')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('sequence', models.TextField()),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Reference')),
            ],
        ),
        migrations.AddField(
            model_name='references',
            name='contig',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gene.ReferenceSequence'),
        ),
        migrations.AddField(
            model_name='references',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Reference'),
        ),
        migrations.AddField(
            model_name='features',
            name='inference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Inference'),
        ),
        migrations.AddField(
            model_name='features',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Note'),
        ),
        migrations.AddField(
            model_name='features',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Product'),
        ),
        migrations.AddField(
            model_name='features',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Sample'),
        ),
        migrations.AddField(
            model_name='clustermembers',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Clusters'),
        ),
        migrations.AddField(
            model_name='clustermembers',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene', to='gene.Names'),
        ),
        migrations.AddField(
            model_name='clustermembers',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Organism'),
        ),
        migrations.AddField(
            model_name='clustermembers',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='gene.Names'),
        ),
        migrations.AddField(
            model_name='blastresults',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Features'),
        ),
        migrations.AddField(
            model_name='blastresults',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Program'),
        ),
        migrations.AddField(
            model_name='blastresults',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Sample'),
        ),
        migrations.AlterUniqueTogether(
            name='referencesequence',
            unique_together=set([('reference', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='references',
            unique_together=set([('reference', 'contig', 'cluster', 'start', 'end')]),
        ),
        migrations.AlterUniqueTogether(
            name='features',
            unique_together=set([('sample', 'contig', 'cluster', 'start', 'end')]),
        ),
        migrations.AlterUniqueTogether(
            name='blastresults',
            unique_together=set([('sample', 'feature')]),
        ),
    ]
