# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-03 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0006_auto_20170208_1828'),
        ('gene', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Annotation')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.Clusters')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Reference')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='references',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='references',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='references',
            name='contig',
        ),
        migrations.RemoveField(
            model_name='references',
            name='reference',
        ),
        migrations.AlterUniqueTogether(
            name='referencesequence',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='referencesequence',
            name='reference',
        ),
        migrations.DeleteModel(
            name='References',
        ),
        migrations.DeleteModel(
            name='ReferenceSequence',
        ),
        migrations.AlterUniqueTogether(
            name='referencemapping',
            unique_together=set([('reference', 'annotation', 'cluster')]),
        ),
    ]
