# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-04 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0002_auto_20170403_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencemapping',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gene.Product'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='referencemapping',
            unique_together=set([('reference', 'annotation', 'cluster', 'product')]),
        ),
    ]
