# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0004_auto_20160421_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastresults',
            name='query_len',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
