# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_scaffolds', models.BooleanField(db_index=True, default=False)),
                ('total_contig', models.PositiveSmallIntegerField()),
                ('total_contig_length', models.PositiveIntegerField()),
                ('min_contig_length', models.PositiveIntegerField()),
                ('median_contig_length', models.PositiveIntegerField()),
                ('mean_contig_length', models.DecimalField(decimal_places=2, max_digits=9)),
                ('max_contig_length', models.PositiveIntegerField()),
                ('n50_contig_length', models.PositiveIntegerField(default=0)),
                ('l50_contig_count', models.PositiveSmallIntegerField(default=0)),
                ('ng50_contig_length', models.PositiveIntegerField(default=0)),
                ('lg50_contig_count', models.PositiveSmallIntegerField(default=0)),
                ('contigs_greater_1k', models.PositiveSmallIntegerField()),
                ('contigs_greater_10k', models.PositiveSmallIntegerField()),
                ('contigs_greater_100k', models.PositiveSmallIntegerField()),
                ('contigs_greater_1m', models.PositiveSmallIntegerField()),
                ('percent_contigs_greater_1k', models.DecimalField(decimal_places=2, max_digits=4)),
                ('percent_contigs_greater_10k', models.DecimalField(decimal_places=2, max_digits=4)),
                ('percent_contigs_greater_100k', models.DecimalField(decimal_places=2, max_digits=4)),
                ('percent_contigs_greater_1m', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contig_percent_a', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contig_percent_t', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contig_percent_g', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contig_percent_c', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contig_percent_n', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contig_non_acgtn', models.DecimalField(decimal_places=2, max_digits=4)),
                ('num_contig_non_acgtn', models.PositiveSmallIntegerField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together=set([('sample', 'is_scaffolds')]),
        ),
    ]
