# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contigs',
            name='is_plasmids',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='stats',
            name='is_plasmids',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterUniqueTogether(
            name='contigs',
            unique_together=set([('sample', 'is_plasmids', 'name')]),
        ),
    ]
