# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_metadata_md5sum'),
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('sequence', models.TextField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MetaData')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contigs',
            unique_together=set([('sample', 'name')]),
        ),
    ]
