# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_auto_20160609_1108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together=set([('sample', 'is_plasmids', 'is_scaffolds')]),
        ),
    ]
