# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_auto_20160609_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='contig_non_acgtn',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='contig_percent_a',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='contig_percent_c',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='contig_percent_g',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='contig_percent_n',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='contig_percent_t',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='percent_contigs_greater_100k',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='percent_contigs_greater_10k',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='percent_contigs_greater_1k',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='percent_contigs_greater_1m',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
