# Generated by Django 2.0 on 2017-12-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_auto_20171216_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='contigs_greater_100k',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='contigs_greater_10k',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='contigs_greater_1k',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='contigs_greater_1m',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='l50_contig_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='lg50_contig_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='num_contig_non_acgtn',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='total_contig',
            field=models.PositiveIntegerField(),
        ),
    ]
